apiVersion: example.com/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: cluster-sample
spec:
  # TODO(user): Add fields here
